In [1]:
import pandas as pd

In [4]:
pathtocsv=r'https://docs.google.com/spreadsheets/d/e/2PACX-1vTMh9zRp8UQVAN2J2v6zUWEx_APMMJLPAW3G-OhkCvNhyKp0JEPMJtChnbyBDWpRhh6RoMMmbPUb72r/pub?output=csv'

In [5]:
df = pd.read_csv(pathtocsv)

In [6]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,"3,39",17850.0,United Kingdom
1,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/10 8:34,"1,69",13047.0,United Kingdom
2,536367,21755,LOVE BUILDING BLOCK WORD,3,12/1/10 8:34,"5,95",13047.0,United Kingdom
3,536368,22914,BLUE COAT RACK PARIS FASHION,3,12/1/10 8:34,"4,95",13047.0,United Kingdom
4,536373,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 9:02,"2,75",17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
54209,581585,84832,ZINC WILLIE WINKIE CANDLE STICK,24,12/9/11 12:31,"0,85",15804.0,United Kingdom
54210,581585,23084,RABBIT NIGHT LIGHT,12,12/9/11 12:31,"2,08",15804.0,United Kingdom
54211,581585,84692,BOX OF 24 COCKTAIL PARASOLS,25,12/9/11 12:31,"0,42",15804.0,United Kingdom
54212,581587,22631,CIRCUS PARADE LUNCH BOX,12,12/9/11 12:50,"1,95",12680.0,France
54213,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/11 12:50,"4,15",12680.0,France